config/routes.rb
Rails.application.routes.draw do
  
  delete '/sessions' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:index, :new, :create, :show]

  resources :posts do 
    resources :comments
   end
  
root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy

# // =========================================================================================
# Validators to ensure the title of the post is there and meets minimum length, same for body
# // =========================================================================================
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user
  def current_user
    User.where(id: session["user_id"]).first
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
	@comment .destroy

	redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

# This allows us when we are on the post page to save create and save a post
	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

def show
	@post = Post.find(params[:id])
end

def edit
	@post = Post.find(params[:id])
end

def update 
	@post = Post.find(params[:id])
	if @post.update(params[:post].permit(:title, :body))
		redirect_to @post
	else
		render 'edit'
	end 	
end

def destroy
	@post = Post.find(params[:id])
	@post.destroy
	redirect_to root_path 
end



private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new #Any controller can create something from any other model!
    if params[:user_created] == 'true'
      @user_created_message = 'User successfully created!'
    end
  end


  def create
    # raise params.inspect
    #Find the user by email
    u = User.where(email: params[:user][:email]).first #in the params hash, you can pick up the user hash, within which you can pick up the email key-value pair
    if u !=nil && u.authenticate(params[:user][:password]) #check that there is a user found and the password is correct
      session['user_id'] = u.id.to_s # hold on to idea that you are logged in, which is the session state. This is a special rails magic thing. This capitalized session has nothing to do with a model or even this controller which is called sessions. The Session in this case refers to something in Rails that essentially is a cookie that will be passed around as long as the next page renders correctly
      redirect_to user_path(u) #should redirect to a dashboard. Just want to redirect to a page that we currently have
    end
  end

  def destroy
    session.destroy
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# // =================================================================================
# Shout out to K. Curbelo for User Authentication markup
# // =================================================================================

  def new
    @user = User.new
  end

  def create
    user = User.new(params.require(:user).permit(:first_name, :email, :password)) #which inputs will be allowed in the create controller
    if user.save
      redirect_to new_session_path(user_created: 'true') #someone logs in here
    end
  end

  def show
    @user = User.find(session['user_id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
    </div>

<p><%= link_to 'Delete', [comment.post, comment],
    method: :delete,
    class: 'button',
    data: { confirm: 'Are you sure?'} %>
</p>

</div>

app/views/comments/_form.html.erb
 <%= form_for([@post, @post.comments.build]) do |f| %>
<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
</p>
<br>
<p>
	<%= f.label :body %><br>
    <%= f.text_area :body %><br>
</p>    
<br>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P2blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Creates the div's for the side bar which contains the logo -->
<%= session["user_id"].inspect %>
<div id="sidebar">
<div id="logo">
	<%= link_to root_path do %>
		<%= image_tag "blog.png"%>
		<% end %>
</div>

<!-- Creates a link to the home page of the blog -->
	<ul>
		<li class="category"> Website</li>
		<li><%= link_to "Blog", root_path %></li>
		<li>About</li>
	</ul>
<!-- Creates social media links -->
	<ul>
		<li class="category">Social Media</li>
		<!-- <li><a href="twitter link">Twitter</a></li> -->
		<!-- <li><a href="instagram link">Instrgram</a></li> -->
		<li><a href="https://www.facebook.com">Facebook</a></li>
		<!-- <li><a href="github link">GitHub</a></li> -->
	</ul>
<!-- Create a p tag for a Admin Login -->
	<!-- <p class="sign_in">Admin Login</p>	 -->
</div>

<div id="main_content">
	<div id="header">
		<button class="button"><%= link_to "All Posts", posts_path %></button>
			<div class="buttons">
		
				  

			      <% if current_user != nil %>
			      <button class="button"><%= link_to "Log out", logout_path, method: :delete %></button>
			      <button class="button"><%= link_to "New Post", new_post_path %></button>

			      <% else %>

			      <button class="button"><%= link_to "Sign up", new_user_path %></button>
			      <!--<div id="signUp"><%#= link_to "Sign up", new_user_path, method: :get %></div>-->
			      <button class="button"><%= link_to "Log in", new_session_path %></button>
			      <% end %>

			</div>
	</div>

	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert") %>
	<% end %>	

<%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<!-- Creating a form to input a post from the posts new page -->
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>
	<% end %>

<!-- This creates the title for the blog on the post page  -->
<p>
<%= f.label :title %> <br>
<%= f.text_field :title %> 
</p>
<!-- This creates the text for the new post -->
<p>
	<%= f.label :body %> <br>
	<%= f.text_area :body %>
</p>
<!-- This is the submit button -->
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">

<h1> Edit Post </h1>

<%= render 'form' %> 

</div>

app/views/posts/index.html.erb
<% @post.each do |post| %>
	<div class="post_wrapper">
	<h2 class="title"> <%= link_to post.title, post %> </h2>
	<p class="date"><%= post.created_at.strftime("%B, %d, %Y")%></p>
</div>

<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">

<h1> New Post </h1>

<!-- Creating a form to input a post from the posts new page -->
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>
	<% end %>

<!-- This creates the title for the blog on the post page  -->
<p>
<%= f.label :title %> <br>
<%= f.text_field :title %> 
</p>
<!-- This creates the text for the new post -->
<p>
	<%= f.label :body %> <br>
	<%= f.text_area :body %>
</p>
<!-- This is the submit button -->
<p>
	<%= f.submit %>
</p>
<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
<h1 class="title">
<%= @post.title %>
</h1>

<p class="date">
Submitted <%= time_ago_in_words(@post.created_at) %> Ago
| <%= link_to 'Edit', edit_post_path(@post) %>
| <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
</p>

<p class="body">
<%= @post.body %>
</p>

	<div id="comments">
		<h2> <%= @post.comments.count %> Comments </h2>
		<%= render @post.comments %>

		<h3>Add a comment:</h3>	
		<%= render "comments/form" %>
	
	</div>
</div>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f|%>
    First name: <%= f.text_field :first_name %><br />
    E-mail: <%= f.text_field :email %><br />
    Password: <%= f.password_field :password %><br />
    Password confirmation: <%= f.password_field :password_confirmation %><br />

    <%=f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome to your use page <%= @user.email%> !</h1>
<p>You are now logged in.</p>
<p>E-mail:</p>
<%= @user.email %>